---
# Homepage configuration
# See https://fontawesome.com/icons for icons options

title: "Jeppe Klitgaard"
subtitle: "ğŸ  Home"
logo: "logo.png"
# icon: "fas fa-skull-crossbones" # Optional icon

header: true
footer: false

# Optional theme customization
theme: default
colors:
  light:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#ffffff"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link-hover: "#363636"
  dark:
    highlight-primary: "#3367d6"
    highlight-secondary: "#4285f4"
    highlight-hover: "#5a95f5"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link-hover: "#ffdd57"

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "GitHub"
    icon: "fab fa-github"
    url: "https://github.com/JeppeKlitgaard"
    target: "_blank" # optional html a tag target attribute

# Services
# First level array represent a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Reading"
    icon: "fas fa-book"
    items:
      - name: "Tiny Tiny RSS"
        logo: "assets/webapps/ttrss.png"
        subtitle: "ğŸ“° News and stuff"
        tag: "app"
        url: "https://rss.jeppe.science/"
        # target: "_blank" # optional html a tag target attribute

      - name: "RSS Bridge"
        logo: "assets/webapps/rssbridge.png"
        subtitle: "ğŸŒ‰ For setting up RSS feeds on other sources"
        tag: "app"
        url: "https://rssbridge.jeppe.science/"

      - name: "Wallabag"
        logo: "assets/webapps/wallabag.png"
        subtitle: "ğŸ“š For catching up on read stuff"
        tag: "app"
        url: "https://read.jeppe.science/"

  - name: "Sys Admin"
    icon: "fas fa-tools"
    items:
      - name: "Traefik"
        logo: "assets/webapps/traefik.svg"
        subtitle: "ğŸš§ For building routes"
        tag: "app"
        url: "https://traefik.jeppe.science/"

      - name: "Portainer"
        logo: "assets/webapps/portainer.svg"
        subtitle: "ğŸ” Monitoring containers"
        tag: "app"
        url: "https://portainer.jeppe.science/"

  - name: "Website"
    icon: "fas fa-comment-dots"
    items:
      - name: "Website"
        logo: "assets/websites/jeppe_science.png"
        subtitle: "ğŸ•¸ My personal website"
        tag: "site"
        url: "https://jeppe.science/"

      - name: "Netlify"
        logo: "assets/websites/netlify.svg"
        subtitle: "ğŸ”Œ Deployment"
        tag: "site"
        url: "https://app.netlify.com/teams/jeppeklitgaard/overview"

      - name: "Umami"
        logo: "assets/webapps/umami.svg"
        subtitle: "ğŸ“ˆ For analysing visits"
        tag: "app"
        url: "https://analytics.jeppe.science/website/1/jeppe.science"

      - name: "Remark42"
        logo: "assets/webapps/remark42.png"
        subtitle: "ğŸ’¬ For comments and debate"
        tag: "app"
        url: "https://comments.jeppe.science/web/"

      - name: "Google Search"
        logo: "assets/websites/google_search_console.png"
        subtitle: "ğŸ“Š For seeing search rank"
        tag: "site"
        url: "https://search.google.com/u/1/search-console/performance/search-analytics?resource_id=sc-domain%3Ajeppe.science"
